# Generated by Django 3.2.25 on 2024-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
